### ISSUE TITLE
User add not working?

### ISSUE THREAD

**Issue by dingo35** [subdavis/kobo-book-downloader#85] opened 2022-05-12 10:08 UTC
Hi, when I'm trying to add a user, all the procedure up and until the Captcha goes ok; when I copy the captcha in Firefox, I don't paste it, but go back to the running kobodl (command-line) and press "enter after copying the captcha code..."

Then nothing happens. Am I doing something wrong or have I discovered a bug?

**Comment by subdavis** [comment] 2022-05-12 12:34
> Then nothing happens.

Could you be more specific about the nothing that happens?  Does the program exit, or does it get stuck?  If it's stuck, kobo.com's servers are refusing to answer your request.

If it exits without printing anything, that's a bug.

**Comment by dingo35** [comment] 2022-05-12 12:48
Thanks for your quick response; it's the first, the program gets stuck, probably waiting for Kobos servers.

I always have to login with a bol.com account, perhaps that is the problem?

Brandon Davis ***@***.***> schreef op 12 mei 2022 14:34:21 CEST:

**Comment by subdavis** [comment] 2022-05-12 13:37
Closing as duplicate of #84

**Closed by subdavis** 2022-05-12 13:37 UTC
