### ISSUE TITLE
ConnectionResetError while authorizing.

### ISSUE THREAD

**Issue by TiredFerreira** [subdavis/kobo-book-downloader#87] opened 2022-08-07 02:57 UTC
Hello, I can't get past the captcha.
I've a kobo acc, I tried using python 3.9 with no success so I tried with the powershell wget.
A thing that might be useful to know is that whit the https://github.com/TnS-hun/kobo-book-downloader I was able to login and even see my book list, but I was not able to download due to 'DRMType: 'KDRM', UrlFormat: 'EPUB3FL'.

**Steps to reproduce the behavior:**
1. user add
2. put e-mail and password twice
3. do the whole console stuff to get the captcha
4. get the captcha, copy it and press enter, freezes then after some time it throws an error
```
 `Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 444, in _make_request
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 444, in _make_request
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kobodl\__main__.py", line 5, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 33, in new_func
  File "kobodl\commands\user.py", line 78, in add
  File "kobodl\actions.py", line 169, in Login
  File "kobodl\kobo.py", line 457, in Login
  File "kobodl\kobo.py", line 144, in __GetExtraLoginParameters
  File "requests\sessions.py", line 542, in get
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))`
```

**Expected behavior**

**Screenshots**
![errorss](https://user-images.githubusercontent.com/6692385/183272950-5c0bbfc5-9f95-4848-a55f-b49a3b961de5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
-  Install method and python version: tried with python 3.9 and powershell wget
 - Kobodl Version 0.92

**Additional context**
A thing I noticed, not sure if it's important, the code I got from https://github.com/TnS-hun/kobo-book-downloader captcha was way smaller than the one I got from KoboDL!

**Comment by bybpow** [comment] 2022-08-21 23:29
It is working for me although I got to do some tries. I think the problem is from copy-pasting from console to terminal. Try to paste it before to some notepad.

**Comment by RichardArc** [comment] 2022-10-23 18:15
I was having this issue too, not being able to add the user (it would just hang after entering captcha) and likewise was able to get the original fork to add the user and list but not download.
Never got it to work with the python version but I finally got it to work by using the compiled binary (windows in my case). Maybe try that?

I see on https://pypi.org/project/kobodl is has up to python 3.9 listed, andIhave 3.10, maybe that's causing the issue? Not sure didn't test the theory

**Comment by subdavis** [comment] 2022-12-20 04:14
Has nothing to do with the captcha length, that's a "Connection reset error" which means the kobo servers were closing your connection.  Never seen this, not something I'm able to troubleshoot.

I have never tried this tool outside the united states and can't predict how it will function.  If you can VPN into the US, that might be a good idea to try.

**Closed** 2023-01-29 17:11 UTC
Labels: bug
